/** @jsxImportSource theme-ui */
import Head from "next/head"

import Header from "@/components/Header/Header"
import { Flex, Heading, Text } from "@theme-ui/components"
import { WalletNFTs } from "@/components/WalletNFTs/WalletNFTs"

export default function Home() {
  return (
    <>
      <Head>
        <title>Solana Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main
        sx={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          marginTop: "4rem",
        }}
      >
        <Heading mb=".8rem" variant="heading1">
          Solana Web App template
        </Heading>
        <Text>Quickstart template to build Solana web3 applications</Text>

        <Flex my="3.2rem">
          <WalletNFTs />
        </Flex>
      </main>

      <footer
        sx={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          marginTop: "4rem",
        }}
      >
        <a
          href="https://twitter.com/magicshards"
          target="_blank"
          rel="noopener noreferrer"
          sx={{
            display: "flex",
            alignItems: "center",
          }}
        >
          Powered by{" "}
          <Text
            variant="small"
            sx={{
              display: "flex",
              alignItems: "center",
            }}
          >
            <img
              sx={{
                height: "32px",
              }}
              src="/magicshards.png"
              alt="Magic Shards"
              height={32}
            />
            MagicShards
          </Text>
        </a>
      </footer>
    </>
  )
}
